apiVersion: apps/v1
kind: Deployment
metadata:
        name: messaging-app-blue
        spec:
                replicas: 2
                selector:
                        matchLabels:
                                app: messaging-app
                                version: blue
                template:
                        metadata:
                                labels:
                                        app: messaging-app
                                        version: blue
                        spec:
                                containers:
                                        - name: messaging-app
                                          image: your-django-image:1.0   # <-- existing image version
                                          ports:
                                                  - containerPort: 8000
