version: "3.9"

services:
          web:
                      build: .
                          command: python3 manage.py runserver 0.0.0.0:8000
                              volumes:
                                            - .:/app
                                                  ports:
                                                                - "8000:8000"
                                                                      env_file:
                                                                                    - .env
                                                                                          depends_on:
                                                                                                        - db

                                                                                                            db:
                                                                                                                        image: mysql:5.7
                                                                                                                            environment:
                                                                                                                                          MYSQL_DATABASE: messaging_app
                                                                                                                                                MYSQL_USER: root
                                                                                                                                                      MYSQL_PASSWORD: rootpassword
                                                                                                                                                            MYSQL_ROOT_PASSWORD: rootpassword
                                                                                                                                                                ports:
                                                                                                                                                                              - "3306:3306"

