apiVersion: apps/v1
kind: Deployment
metadata:
        name: messaging-app-green
        spec:
                replicas: 2
                selector:
                        matchLabels:
                                app: messaging-app
                                version: green
                                template:
                        metadata:
                                labels:
                                        app: messaging-app
                                        version: green
                        spec:
                                containers:
                                        - name: messaging-app
                                          image: your-django-image:2.0   # <-- updated image version
                                          ports:
                                                  - containerPort: 8000
